# .air.toml para Windows

cmd = "go run ./cmd/api"
bin = "tmp/air-app.exe"
full_bin = ""
watch_dir = "."
exclude_dir = ["docs", "web", "tmp", "bin"]
include_ext = ["go", "mod", "sum", "env", "yaml", "toml"]
kill_delay = 500
poll = false

[log]
time = true
color = true

[build]
cmd = "go build -o ./tmp/air-app.exe ./cmd/api"
bin = "tmp/air-app.exe"
delay = 100
stop_on_error = true

[misc]
clean_on_exit = true
